targets:
  $default:
    builders:
      example|copyable: { generate_for: ["lib/copyable_example.dart"] }
      example|api_endpoint: { generate_for: ["lib/api_example.dart"] }

builders:
  copyable:
    import: "package:example/_code_builders/copyable/builder.dart"
    builder_factories: ["copyableBuilder"]
    build_extensions:
      { "{{dir}}/{{file}}.dart": ["{{dir}}/_gen/{{file}}.gen.copyable.dart"] }
    auto_apply: none
    build_to: source

  api_endpoint:
    import: "package:example/_code_builders/api_endpoint/builder.dart"
    builder_factories: ["apiEndpointBuilder"]
    build_extensions:
      {
        "{{dir}}/{{file}}.dart":
          ["{{dir}}/_gen/{{file}}.gen.api_endpoint.dart"],
      }
    auto_apply: none
    build_to: source
