///##################################################
///## Generated by message_creator - Do Not Modify ##
///##################################################
class MessageManager {
  String get AppleMessage => "Start Ready to eat End Start Ready to eat End";
  String get BananaMessage => "This fruit can be peeled and enjoyed as a healthy snack";
  MessageManager.tulu();
}
