builders:
  message_creator:
    import: "package:message_creator_gen/message_creator_gen.dart"
    builder_factories: ["messageCreatorBuilder"]
    build_extensions:
      {
        "{{dir}}/{{file}}.dart":
          ["{{dir}}/gen/{{file}}.gen.message_creator.dart"],
      }
    auto_apply: none
    build_to: source
